steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_IMAGE_NAME:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcq-app-image' # Changed to your service name
      - '--image'
      - '$_IMAGE_NAME:$COMMIT_SHA'
      - '--region'
      - 'europe-west4' # Changed to your region
images:
  - '$_IMAGE_NAME:$COMMIT_SHA'
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'
